# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2063101b7bcea88ee806bf1d982b25bc3ff9bc0a869bb3835f48bd300670e8d60053b40b684b58da29ac1e22b757edeb83286992f252ec5e8abc0e431b7a7197

test:
  secret_key_base: 0bfeaab4f9fa29c371357ef554d85b813db0be7078f22af315ddfe94215dadb761c804c4ffc467f49c74522199548525b1a55ce34c5fd00e21256f81711de7d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
