# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49530af9a8cebe72d121fef97728ae25ed4020a1fcae94757ff52c4f01738ebb12b0179c4eaa264aae81495ac7bef470cb445300f60ceacf9df54fea8f7ff1f0

test:
  secret_key_base: 88e87966fed5bc2513c6bad4c6846b0c2b6494d55d852926f5a0cc3ac8ff0b50d237f099e08009c8f1435527bb3703e9841cb27112720a85614803e523680099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
